version: '3.7'
services:
  sellingo_mysql:
    image: mariadb:11.7.1-rc
    container_name: sellingo_mysql
    ports:
      - "5307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sellingo
      MYSQL_USER: sellingo
      MYSQL_PASSWORD: 123
    volumes:
      - ./data/mysql:/var/lib/mysql
    networks:
      sellingo:
        ipv4_address: 172.61.0.3
  sellingo_php:
    build:
      context: docker/php8.2-fpm
      args:
        TIMEZONE: "Europe/Warsaw"
    container_name: sellingo_php
    ports:
      - "9004:9004"
    volumes:
      - ./:/var/www/sellingo:cached
      - ./docker/logs/sellingo:/var/logs:cached
      - ./var/data:/var/data:cached
    links:
      - sellingo_mysql
    extra_hosts:
      - "docker-host.localhost:127.0.0.1"
    networks:
      sellingo:
        ipv4_address: 172.61.0.2
  sellingo_nginx:
    build: docker/nginx
    container_name: sellingo_nginx
    ports:
      - "8089:8089"
      - "9099:443"
    links:
      - sellingo_php
    volumes:
      - ./docker/logs/nginx:/var/logs/nginx:cached
      - ./:/var/www/sellingo:cached
    networks:
      sellingo:
        ipv4_address: 172.61.0.4
        aliases:
          - docs.localhost

networks:
  sellingo:
    driver: bridge
    ipam:
      config:
        - subnet: 172.61.0.0/24

volumes:
  redis-data: